"""Initial tables

Revision ID: 95fe71fbb867
Revises: 
Create Date: 2025-01-02 18:47:40.729944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fe71fbb867'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('global_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', terroroftinytown.tracker.model.JsonType(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_version', sa.Integer(), nullable=False),
    sa.Column('min_client_version', sa.Integer(), nullable=False),
    sa.Column('alphabet', sa.String(), nullable=False),
    sa.Column('url_template', sa.String(), nullable=False),
    sa.Column('request_delay', sa.Float(), nullable=False),
    sa.Column('redirect_codes', terroroftinytown.tracker.model.JsonType(), nullable=False),
    sa.Column('no_redirect_codes', terroroftinytown.tracker.model.JsonType(), nullable=False),
    sa.Column('unavailable_codes', terroroftinytown.tracker.model.JsonType(), nullable=True),
    sa.Column('banned_codes', terroroftinytown.tracker.model.JsonType(), nullable=True),
    sa.Column('body_regex', sa.String(), nullable=True),
    sa.Column('location_anti_regex', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('autoqueue', sa.Boolean(), nullable=True),
    sa.Column('num_count_per_item', sa.Integer(), nullable=False),
    sa.Column('max_num_items', sa.Integer(), nullable=False),
    sa.Column('lower_sequence_num', sa.Integer(), nullable=False),
    sa.Column('autorelease_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('hash', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('lower_sequence_num', sa.Integer(), nullable=False),
    sa.Column('upper_sequence_num', sa.Integer(), nullable=False),
    sa.Column('datetime_claimed', sa.DateTime(), nullable=True),
    sa.Column('tamper_key', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('shortcode', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('encoding', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_project_id'), 'results', ['project_id'], unique=False)
    op.create_table('error_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_reports')
    op.drop_index(op.f('ix_results_project_id'), table_name='results')
    op.drop_table('results')
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('global_settings')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
