[database]
path: sqlite:////tmp/tinyunittest.db

[redis]
host: localhost
port: 6379
password:
db: 0
unix:
prefix: tott_test:
max_stats: 30

[iaexporter]
access_key: invalid-access-key
secret_key: invalid-secret-key
endpoint: s3.us.archive.org
collection: test_collection
format: beacon
last_export_file: last_export.txt
item: urlteam_{timestamp}
timestamp: {year:04d}-{month:02d}-{day:02d}-{hour:02d}-{minute:02d}-{second:02d}
title: URLTeam Release {timestamp} TEST TEST TEST
mediatype: software
description: URLTeam's rolling release of unshortened URLs.
