name: Python test

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements-tracker.txt
        pip install -r requirements-test.txt
    - name: Run unit tests
      run: |
        NO_LIVE_SERVICE_TEST=1 NO_SELENIUM_TEST=1 python -m unittest discover terroroftinytown -p '*test.py'
    - name: Run Selenium tests
      continue-on-error: true
      run: |
        NO_LIVE_SERVICE_TEST=1 RUN_CHROMEDRIVER_HEADLESS=1 python -m unittest terroroftinytown.tracker.test
